---
title: ¿Cómo calcular la incertidumbre de una curva de calibración?
author: cgomez
date: "2017-08-13T10:00:00"
slug: como-calcular-la-incertidumbre-de-una-curva-de-calibracion
categories:
  - incertidumbre
tags: []
---

Ok, este es el segundo post y es 'levemente' más serio que el anterior, pero
aún en rodaje.

>¿Qué es y cómo estimar la incertidumbre de una curva de calibración?

La incertidumbre de calibración, en adelante $u(x_{0})$, es aquella que se 
propaga cuando obtenemos la concentración de un mensurando
al interpolar una señal instrumental (por ejemplo, absorbancia o 
área cromatográfica) en una curva de calibración. Básicamente, 
esta incertidumbre
sólo da cuenta de error aleatorio del instrumento y no incopora la
incertidumbre de los calibrantes, al menos cuando se utiliza el modelo de 
calibración clásico:

\begin{equation}
  y = \beta_{0} + \beta_{1} x + \epsilon
    (\#eq:lin)
\end{equation}

A partir de la ecuación \@ref(eq:lin) obtenemos la concentración de una 
muestra problema $x_{0}$ cuya señal instrumental es $y_{0}$:

\begin{equation}
  x{0} = \frac{y_{0} - \beta_{0}}{\beta_{1}}
    (\#eq:x0)
\end{equation}

Sin embargo, ya que la señal instrumental tiene un error aleatorio $\epsilon$ 
(que se asume Normal con media 0 y varianza $\sigma_{y/x}^2$) la muestra problema, 
al ser obenida por interpolación, tiene una incertidumbre estándar de:

\begin{equation}
  u(x_{0}) = \frac{\sigma_{y/x}}{\beta_{1}}
  \sqrt{\frac{1}{n} + \frac{1}{m_{0}} + \frac{(x_{0} - \overline{x})^2}
  {\sum_{i}^{n} (x_{i} - \overline{x})}}
    (\#eq:ux0)
\end{equation}

Esta incertidumbre se puede observar en la figura \@ref(fig:banda), la
cual es obtenida mediante simulació en kenguaje `R`:

```{r banda, fig.cap = 'Incertidumbre de calibración'}

set.seed(123)
x <- 1:10
y <- 5*x + 3*rnorm(length(x), 0, 1)
d <- data.frame(x, y)

library(ggplot2)

ggplot(d, aes(x = x, y = y)) +
  geom_point(pch = 19, col = 'red') +
  geom_smooth(method = 'lm')

```


Ok, vamos a analizar cada uno de los términos.
